mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^accounts1/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
    url(r'^$', RedirectView.as_view(url='/post/', permanent=True)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^comments/', include('django_comments_xtd.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
#from .views import emailView, successView
from . import views
from .templatetags.abc import *

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^posts/$', views.PostListView.as_view(), name='posts'),
	url(r'^proposed_posts/$', views.ProposedPostListView.as_view(), name='proposed_posts'),
	url(r'^profile/(?P<pk>\d+)$', views.ProfileDetailView.as_view(), name='profile-detail'),
	url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post-detail'),
	url(r'^profiles/$', views.ProfileListView.as_view(), name='profiles'),
	url(r'^post/create/$', views.PostCreateView.as_view(), name='post_create'),
	url(r'^post/(?P<pk>\d+)/update/$', views.PostUpdateView.as_view(), name='post_update'),
	url(r'^post/(?P<pk>\d+)/comment_update/$', views.CommentUpdateView.as_view(), name='comment_update'),
	url(r'^post/(?P<pk>\d+)/delete/$', views.PostDelete.as_view(), name='post_delete'),
	url(r'^post/(?P<pk>\d+)/comment_delete/$', views.CommentDelete.as_view(), name='comment_delete'),
	url(r'^profile/(?P<pk>\d+)/update/$', views.ProfileUpdateView.as_view(), name='profile_update'),
	url(r'^profile/(?P<pk>\d+)/updatephoto/$', views.ProfileUpdatePhotoView.as_view(), name='profile_update_photo'),
	url(r'^search/$', views.SearchView.as_view(), name='search_view'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^thanks/$', views.thanks, name='thanks'),
	# url(r'^moderator-approval/(?P<pk>\d+)$', views.moderator_approval_view, name="moderator-approval"),
	url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
	#url(r'email/$', emailView, name='email'),
	#url(r'success/$', successView, name='success'),
]

post/models.py
from django.db import models
from datetime import date, datetime
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from django import forms
from stdimage.models import StdImageField

def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)


class Profile(models.Model):
    SEX = [
        ("Женский","Женский"),
        ("Мужской","Мужской")
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='', default='')
    first_name = models.CharField(verbose_name='Имя', max_length=30, default='')
    last_name = models.CharField(verbose_name='Фамилия', max_length=30, default='')
    avatar = models.ImageField(upload_to='upload_location', verbose_name="Аватар", default='')
    city = models.CharField(verbose_name='Город', max_length=20, default='')
    email = models.EmailField(max_length=30, default='')
    sex = models.CharField(verbose_name='Пол', max_length=7,
        choices=SEX, default='')
    contacts = models.TextField(verbose_name='Контакты', max_length=150, blank=True, null=True, default='')
    biography = models.TextField(verbose_name='Биография', max_length=400, blank=True, null=True, default='')
    other_info = models.TextField(verbose_name='Прочая информация', max_length=400, blank=True, null=True, default='')
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True, blank=True, null=True)

    class Meta:
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse('profile-detail', args=[str(self.id)])

    def __str__(self):
        return self.user.username

from django.utils.html import escape

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=50)
    body = RichTextUploadingField()
    logo = StdImageField(upload_to=upload_location,variations={'thumbnail': {"width": 150, "height": 150, "crop": True}}, default='')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    moderation = models.BooleanField(default=False)
    post_date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    description = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-comment_date"]

    def __str__(self):
        return "{}".format(self.description)

post/forms.py
from django import forms
from .models import Profile, Post, Comment
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime

class SignupForm(UserCreationForm):
    city = forms.CharField(label='Город')
    contacts = forms.CharField(label='Контакты', widget=forms.Textarea, required=False)
    biography = forms.CharField(label='Биография', widget=forms.Textarea, required=False)
    other_info = forms.CharField(label='Другая информация', widget=forms.Textarea, required=False)
    avatar = forms.ImageField(label='Аватар', required=False)
    SEX = [
        ("Женский","Женский"),
        ("Мужской","Мужской")
    ]
    sex = forms.ChoiceField(label=u'Пол', choices = SEX)

    class Meta:
        model = User
        fields = ('username', 'avatar', 'first_name', 'last_name', 'email',
            'password1', 'password2', 'city', 'sex',
             'biography', 'contacts', 'other_info')


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False)
    class Meta:
        model = Profile
        exclude = ('user', )

class ContactForm(forms.Form):
    subject = forms.CharField(required=True, label="Тема")
    contact_name = forms.CharField(required=True, label="Имя")
    contact_email = forms.EmailField(required=True, label="Email")
    content = forms.CharField(widget=CKEditorUploadingWidget(), required=True, label="Сообщение")


class PostForm(forms.ModelForm):        
    class Meta:
        model = Post
        fields = ['title', 'body', 'logo']


class CommentForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea, label='')
    class Meta:
        model = Comment
        fields = ['description']

post/views.py
from .models import Profile, Post, Comment
from .forms import ProfileForm, PostForm, ContactForm, CommentForm
from django.views import generic, View
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
# from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.core.mail import EmailMessage, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse

from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            city = form.cleaned_data.get('city')
            biography = form.cleaned_data.get('biography')
            contacts = form.cleaned_data.get('contacts')
            avatar = form.cleaned_data.get('avatar')
            sex = form.cleaned_data.get('sex')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            other_info = form.cleaned_data.get('other_info')
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            profile = user.profile
            profile.city = city
            profile.email = email
            profile.avatar = avatar
            profile.first_name = first_name
            profile.last_name = last_name
            profile.biography = biography
            profile.contacts = contacts
            profile.sex = sex
            profile.other_info = other_info
            profile.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


# class Home(TemplateView):
#     template_name = 'index.html'

from django.utils.http import is_safe_url, urlunquote
from django.conf import settings
import geoip2.database
import requests

PRIVATE_IPS_PREFIX = ('10.', '172.', '192.', )
def index(request):
    num_posts=Post.objects.all().count()
    num_visits=request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1


    remote_address = request.META.get('REMOTE_ADDR')
    ip = remote_address
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        proxies = x_forwarded_for.split(',')
        while (len(proxies) > 0 and
                proxies[0].startswith(PRIVATE_IPS_PREFIX)):
            proxies.pop(0)
        if len(proxies) > 0:
            ip = proxies[0]

    reader = geoip2.database.Reader('post/GeoLite2-City_20190108/GeoLite2-City.mmdb')
    try:
        city = reader.city(ip).city.name
    except:
        city = 'Dnipro'

    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&lang=ru&appid=4e328f5a34221d8b56cc9e2f55417a76'
    city_weather = requests.get(url.format(city)).json()

    weather = {
        'city' : city,
        'temperature' : str(city_weather['main']['temp'])+'°C,',
        'description' : city_weather['weather'][0]['description'],
        'icon' : city_weather['weather'][0]['icon']
    }

    next = request.META.get('HTTP_REFERER')
    if next:
        next = urlunquote(next)  # HTTP_REFERER may be encoded.
    if not is_safe_url(url=next, allowed_hosts={request.get_host()}):
        next = '/'
    return render(
        request,
        'index.html',
        context={'num_posts':num_posts, 'num_visits':num_visits, 'ip': ip, 'next': next, 'city': city, 'weather' : weather }
        )


class ProfileListView(generic.ListView):
    model = Profile
    paginate_by = 5


class ProfileDetailView(generic.DetailView):
    model = Profile


class ProfileUpdateView(UpdateView):
    model = Profile
    fields = ['avatar', 'first_name', 'last_name', 'email', 'city', 'sex',
         'biography', 'contacts', 'other_info']


class ProfileUpdatePhotoView(UpdateView):
    model = Profile
    fields = ['avatar']


class PostCreateView(FormView):
    form_class = PostForm
    template_name = 'post/post_form.html'
    success_url = reverse_lazy('posts')

    def form_valid(self, form):
        response = super(PostCreateView, self).form_valid(form)
        form.instance.user = self.request.user
        form.save()
        return response

from django.forms import modelform_factory

class PostUpdateView(UpdateView):
    model = Post

    def get_form_class(self):
        fields = ['title', 'body', 'logo']
        if self.request.user.is_staff:
            fields.append('moderation')

        return modelform_factory(self.model, fields=fields)

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('posts')

class CommentUpdateView(UpdateView):
    model = Comment
    fields = ['description']
    success_url = reverse_lazy('posts')

class CommentDelete(DeleteView):
    model = Comment
    success_url = reverse_lazy('posts')

class PostListView(generic.ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset()
        return queryset.filter(moderation=True)

class ProposedPostListView(generic.ListView):
    model = Post
    template_name = 'post/proposed_post_list.html'

    def get_queryset(self):
        queryset = super(ProposedPostListView, self).get_queryset()
        return queryset.filter(moderation=False)


class PostDetailView(generic.DetailView):
    model = Post

    def get_context_data(self, **kwargs):
       context = super(PostDetailView, self).get_context_data(**kwargs)
       context['commentform'] = CommentForm()
       return context

    def post(self, request, pk):
       post = get_object_or_404(Post, pk=pk)
       form = CommentForm(request.POST)

       if form.is_valid():
           obj  = form.save(commit=False)
           obj.post = post
           obj.author = self.request.user
           obj.save()
           return redirect('post-detail', post.pk)


class SearchView(View):
	template_name = 'search.html'

	def get(self, request, *args, **kwargs):
		query = self.request.GET.get('q')
		founded = Post.objects.filter(Q(title__icontains=query)|Q(body__icontains=query))
		context = {'founded': founded}
		return render(self.request, self.template_name, context)


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            contact_name = form.cleaned_data['contact_name']
            contact_email = form.cleaned_data['contact_email']
            content = form.cleaned_data['content']

            try:
                email = EmailMessage(subject,
                                    content,
                                    contact_email,
                                    ['dinamo.mutu111@gmail.com'],
                                    reply_to=[contact_email],
                                    )
                email.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('thanks')
    return render(request, 'contact.html', {'form': form})

def thanks(request):
    return render(request, 'thanks.html', {})

post/templates/acc_active_email.html
{% autoescape off %}
Привет, {{ user.username }},
Пожалуйста, нажми на ссылку для подтверждения регистрации.
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

post/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Post</title>{% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  {% load all_comments %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>

<body>
  <div class="main">
    <div class="left-sidebar">
      <div class="weather">
        {% city_weather %}
      </div>
      <div class="menu">
        <ul>
          <li><a href="{% url 'index' %}"><span><i class="fas fa-home"></i> Главная</span></a></li>
          <li><a href="{% url 'posts' %}"><span><i class="fas fa-briefcase"></i> Работы</span></a></li>
          <li><a href="{% url 'contact' %}"><span><i class="fas fa-envelope"></i> Контакты</span></a></li>
          <li><a href="{% url 'profiles' %}"><span><i class="fas fa-users"></i> Профили</span></a></li>
  		    {% if user.is_authenticated %}
  			     <li><a href="{% url 'logout'%}?next={{request.path}}"><span><i class="fa fa-sign-out"></i> Выход</span></a></li>
  		    {% else %}
  			     <li><a href="{% url 'login'%}?next={{request.path}}"><span><i class="fas fa-sign-in"></i> Вход</span></a></li>
  			     <li><a href="{% url 'signup' %}"><span><i class="fas fa-user-plus"></i> Регистрация</span></a></li>
          {% endif %}
        </ul>
      </div>
      <div class="online">
        {% see_users %}
      </div>
    </div>
    <div class="content">
      {% block content %}{% endblock %}
      {% if is_paginated %}
        <div class="pagination">
          <span class="page-current">
            {{ page_obj.number }}
          </span>
          <span class="page-links">
            {% if page_obj.has_previous %}
              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Назад</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Далее</a>
              <a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
          </span>
        </div>
      {% endif %}
    </div>
	  <div class="right-sidebar">
      <div class="search">
        <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
          <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-search-13" viewBox="0 0 40 40">
            <path d="M26.804 29.01c-2.832 2.34-6.465 3.746-10.426 3.746C7.333 32.756 0 25.424 0 16.378 0 7.333 7.333 0 16.378 0c9.046 0 16.378 7.333 16.378 16.378 0 3.96-1.406 7.594-3.746 10.426l10.534 10.534c.607.607.61 1.59-.004 2.202-.61.61-1.597.61-2.202.004L26.804 29.01zm-10.426.627c7.323 0 13.26-5.936 13.26-13.26 0-7.32-5.937-13.257-13.26-13.257C9.056 3.12 3.12 9.056 3.12 16.378c0 7.323 5.936 13.26 13.258 13.26z"
            fill-rule="evenodd" />
          </symbol>
          <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-clear-3" viewBox="0 0 20 20">
            <path d="M8.114 10L.944 2.83 0 1.885 1.886 0l.943.943L10 8.113l7.17-7.17.944-.943L20 1.886l-.943.943-7.17 7.17 7.17 7.17.943.944L18.114 20l-.943-.943-7.17-7.17-7.17 7.17-.944.943L0 18.114l.943-.943L8.113 10z" fill-rule="evenodd" />
          </symbol>
        </svg>

        <form novalidate="novalidate" class="searchbox sbx-google" action="{% url 'search_view' %}" method='GET'>
          <div role="search" class="sbx-google__wrapper">
            <input type="text" name="q" placeholder="Поиск по сайту" autocomplete="off" required="required" class="sbx-google__input">
            <button type="submit" title="Нажми, чтобы найти" class="sbx-google__submit">
              <svg role="img" aria-label="Search">
                <use xlink:href="#sbx-icon-search-13"></use>
              </svg>
            </button>
            <button type="reset" title="Очисть" class="sbx-google__reset">
              <svg role="img" aria-label="Reset">
                <use xlink:href="#sbx-icon-clear-3"></use>
              </svg>
            </button>
          </div>
        </form>
        <script type="text/javascript">
          document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
        </script>
      </div>
      {% if user.is_authenticated %}
        <div class="mini-profile">
          {% if user.is_authenticated %}
            <a href="{{ request.user.profile.get_absolute_url }}">{{ user.profile.user }}</a></br>
            {% if not user.profile.avatar %}
              <img src="{% static 'css/def-avatar.png' %}" width=100px;>
            {% else %}
              <img src="{{STATIC_URL}}{{ user.profile.avatar.url }}" width=100px;>
            {% endif %}
            </br>
            {{ user.profile.first_name }} {{ user.profile.last_name }}</br>
            <span margins-bottom=10px>{{ user.profile.email }}</span></br>
            <a href="{% url 'logout'%}?next={{request.path}}"><span>Выход</span> <i class="fa fa-sign-out"></i></a>
          {% endif %}
        </div>
      {% endif %}
      <div class="last-comments">
        {% comment_list %}
      </div>
    </div>
  </div>
  <div class="footer">

  </div>

  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
  <script src="http://code.jquery.com/jquery-latest.js" type="text/javascript"></script>
  <script src="script.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
  <!-- Begin Verbox {literal} -->
  <script type='text/javascript'>
  (function(d, w, m) {
      window.supportAPIMethod = m;
      var s = d.createElement('script');
      s.type ='text/javascript'; s.id = 'supportScript'; s.charset = 'utf-8';
      s.async = true;
      var id = 'ac7ee42d549c5ec4a7cf69505de57eed';
      s.src = '//admin.verbox.ru/support/support.js?h='+id;
      var sc = d.getElementsByTagName('script')[0];
      w[m] = w[m] || function() { (w[m].q = w[m].q || []).push(arguments); };
      if (sc) sc.parentNode.insertBefore(s, sc);
      else d.documentElement.firstChild.appendChild(s);
  })(document, window, 'Verbox');
  </script>
  <!-- {/literal} End Verbox -->

  <script type="text/javascript">
    $(document).ready(function(){
    $('.spoiler-title').click(function(){
    $(this).parent().children('div.spoiler-content').toggle('fast');
    return false;
    });
    });
  </script>
</body>
</html>

post/templates/contact.html
{% extends 'base_generic.html' %}

{% load widget_tweaks %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

{% block content %}
  <div>
    <div>
      <div>
        <h1>Мои контакты</h1>
        <div>
          <img src="{% static 'css/phone.png' %}" height=20px> +38(066)-108-86-11</br>
          <img src="{% static 'css/skype.svg' %}" height=20px><a href="skype:dinamo.mutu?chat"> dinamo.mutu</a></br>
          <img src="{% static 'css/gmail.png' %}" height=20px><a href="mailto:dinamo.mutu111@gmail.com"> dinamo.mutu111@gmail.com</a></br>
          <img src="{% static 'css/linkedin.png' %}" height=20px><a href="https://www.linkedin.com/in/dmitry-dmytruk-8009a3176/"> https://www.linkedin.com/in/dmitry-dmytruk-8009a3176/</a>
        </div>
      </div>
  </div>
  <br>
  <form class="form-horizontal" role="form" action="." method="post">
    {% csrf_token %}
    {% for field in form %}
      {% if field.errors %}
        <div>
          <label for="id_{{ field.name }}">{{ field.label }}</label>
          <div>
            {{ field|attr:"class:form-control" }}

              {% for error in  field.errors %}{{ error }}{% endfor %}

          </div>
        </div>
        {% else %}
        <div>
          <label for="id_{{ field.name }}">{{ field.label }}</label>
          <div>
            {{ field|attr:"class:form-control" }}
            {% if field.help_text %}
              <p><small>{{ field.help_text }}</small></p>
            {% endif %}
          </div>
        </div>
        {% endif %}
      {% endfor %}
      <div>
        <div>
          <button type="submit">Отправить</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

post/templates/search.html
{% extends 'base_generic.html' %}

{% block content %}

<h4>Найденные результаты: {{ founded.count }}</h4></br>
{% for post in founded %}
  {{ post.title }}
{% endfor %}
{% endblock %}

post/templates/signup.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Регистрация</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}

        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>

        {% endfor %}
      </p>
      </br>
      {% endfor %}
    <button type="submit">Подтвердить</button>
  </form>
{% endblock %}